#define NOT_VALID 255

#define MIN_TEMP 0
#define MIN_SOC 20
#define MIN_CHAEGERATE NOT_VALID

#define MAX_TEMP 45
#define MAX_SOC 80
#define MAX_CHAEGERATE 0.8

#define NOOFBATTERYPROPERTYCHECK 3

#define PASS 1
#define FAIL 0

#define LISTOFLANGUAGE 2
#define EARLYWARNOTNEEDED NOT_VALID

#define LISTOFWARNINGPERPROPERTIES 2

#define LOWType 1
#define HIGHType 2